# Generated by Django 3.1 on 2020-10-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_departure_lat', models.FloatField()),
                ('mar_departure_long', models.FloatField()),
                ('mar_departure_addr', models.CharField(max_length=100)),
                ('mar_departure_phone', models.IntegerField()),
                ('mar_destination_lat', models.FloatField()),
                ('mar_destination_long', models.FloatField()),
                ('mar_destination_addr', models.CharField(max_length=100)),
                ('mar_destination_phone', models.IntegerField()),
                ('mar_item', models.CharField(max_length=100)),
                ('mar_created', models.DateTimeField(auto_now_add=True)),
                ('mar_limit_time', models.CharField(max_length=100)),
                ('mar_weight', models.FloatField()),
                ('mar_distance', models.IntegerField()),
                ('mar_price', models.IntegerField()),
                ('mar_content', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_my_stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_departure_lat', models.FloatField()),
                ('my_departure_long', models.FloatField()),
                ('my_departure_addr', models.CharField(max_length=100)),
                ('my_departure_phone', models.IntegerField()),
                ('my_destination_lat', models.FloatField()),
                ('my_destination_long', models.FloatField()),
                ('my_destination_addr', models.CharField(max_length=100)),
                ('my_destination_phone', models.IntegerField()),
                ('my_created', models.DateTimeField(auto_now_add=True)),
                ('my_limit_time', models.CharField(max_length=100)),
                ('my_goods', models.CharField(max_length=100)),
                ('my_goodsinfo', models.CharField(max_length=30)),
                ('my_weigth', models.FloatField()),
                ('my_distance', models.IntegerField()),
                ('my_price', models.IntegerField()),
                ('my_content', models.CharField(max_length=30)),
            ],
        ),
    ]
