# Generated by Django 3.1.2 on 2020-10-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_market',
            name='mar2_count',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delivery_market',
            name='mar2_item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delivery_market',
            name='mar3_count',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delivery_market',
            name='mar3_item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_market',
            name='mar1_count',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_market',
            name='mar1_item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
