# Generated by Django 3.1.2 on 2020-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_security_number',
            field=models.IntegerField(blank=True),
        ),
    ]
