# Generated by Django 3.1 on 2020-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30)),
                ('good_price', models.IntegerField()),
                ('good_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_lat', models.FloatField()),
                ('store_long', models.FloatField()),
                ('store_addr', models.CharField(max_length=100)),
                ('store_phone', models.IntegerField()),
                ('store_goods', models.ManyToManyField(blank=True, related_name='goods', to='storeApp.Good')),
            ],
        ),
    ]
