# Generated by Django 3.1 on 2020-10-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='good_name',
        ),
        migrations.AddField(
            model_name='good',
            name='good_names',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
