# Generated by Django 3.1 on 2020-10-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_auto_20201011_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='good_names',
            new_name='good_name',
        ),
    ]
